name: Bug report
description: Report a bug to help us improve
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us what you expected to happen.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: input
    id: repro-steps
    attributes:
      label: Reproduction steps (minimal)
      description: Exact steps to reproduce the issue.
    validations:
      required: false
