name: Bug report
description: Report a reproducible problem
labels: [bug]
body:
  - type: textarea
    id: summary
    attributes: { label: Summary, placeholder: What happened and what did you expect? }
    validations: { required: true }
  - type: textarea
    id: repro
    attributes: { label: Reproduction steps, placeholder: Steps, commands, inputs, environment }
  - type: input
    id: version
    attributes: { label: Affected version, placeholder: e.g., v0.1.1 }
  - type: textarea
    id: logs
    attributes: { label: Logs / output, render: shell }
